language: node_js
node_js:
  - "node"

script:
  - yarn run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: build
  committer-from-gh: true
  on:
    branch: master

notifications:
  email: false
