language: node_js
node_js:
  - "node"

branches:
  only:
    - master

script:
  - yarn run build
  - yarn run deploy-ghpages
  - git reset --hard
  - yarn install
  - yarn run build-wmflabs
  - yarn run deploy-wmflabs

notifications:
  email: false
