language: node_js
node_js:
  - "node"

branches:
  except:
    - gh-pages

script:
  - yarn run build

after_success:
  - test $TRAVIS_BRANCH = "master" && yarn run deploy-travis

notifications:
  email: false
